export enum DocumentPrivilege {
	CAN_ADD_DOCUMENT = 'CAN_ADD_DOCUMENT',
	CAN_UPDATE_DOCUMENT = 'CAN_UPDATE_DOCUMENT',
	CAN_HARD_DELETE_DOCUMENT = 'CAN_HARD_DELETE_DOCUMENT',
	CAN_SOFT_DELETE_DOCUMENT = 'CAN_SOFT_DELETE_DOCUMENT',
	CAN_VIEW_ALL_DOCUMENTS = 'CAN_VIEW_ALL_DOCUMENTS',
	CAN_SEARCH_DOCUMENT = 'CAN_SEARCH_DOCUMENT',
	CAN_RESTORE_DOCUMENT = 'CAN_RESTORE_DOCUMENT',
	CAN_DOWNLOAD_DOCUMENT = 'CAN_DOWNLOAD_DOCUMENT',
	CAN_VALIDATE_DOCUMENT = 'CAN_VALIDATE_DOCUMENT',
}
