export enum KeyPrivilege {
	CAN_CREATE_KEY = 'CAN_CREATE_KEY',
	CAN_UPDATE_KEY = 'CAN_UPDATE_KEY',
	CAN_VIEW_ALL_KEYS = 'CAN_VIEW_ALL_KEYS',
	CAN_SOFT_DELETE_KEY = 'CAN_SOFT_DELETE_KEY',
	CAN_HARD_DELETE_KEY = 'CAN_HARD_DELETE_KEY',
	CAN_RESTORE_KEY = 'CAN_RESTORE_KEY',
}
