export enum TagPrivilege {
	CAN_CREATE_TAG = 'CAN_CREATE_TAG',
	CAN_UPDATE_TAG = 'CAN_UPDATE_TAG',
	CAN_VIEW_ALL_TAGS = 'CAN_VIEW_ALL_TAGS',
	CAN_SOFT_DELETE_TAG = 'CAN_SOFT_DELETE_TAG',
	CAN_HARD_DELETE_TAG = 'CAN_HARD_DELETE_TAG',
	CAN_RESTORE_TAG = 'CAN_RESTORE_TAG',
}
