export enum UserPrivilege {
	CAN_UPLOAD_USERS = 'CAN_UPLOAD_USERS',
	CAN_ENABLE_USER = 'CAN_ENABLE_USER',
	CAN_LOCK_USER = 'CAN_LOCK_USER',
	CAN_DELETE_USER = 'CAN_DELETE_USER',
	CAN_ASSIGN_ROLE_TO_USER = 'CAN_ASSIGN_ROLE_TO_USER',
	CAN_ASSIGN_PRIVILEGE_TO_USER = 'CAN_ASSIGN_PRIVILEGE_TO_USER',
	CAN_RETRIEVE_ROLE_FROM_USER = 'CAN_RETRIEVE_ROLE_FROM_USER',
	CAN_RETRIEVE_PRIVILEGE_FROM_USER = 'CAN_RETRIEVE_PRIVILEGE_FROM_USER',
	CAN_VIEW_ALL_USERS = 'CAN_VIEW_ALL_USERS',
	CAN_CHANGE_USER_STATUS = 'CAN_CHANGE_USER_STATUS',
}
